added nginx container and shift to php-fpm from the php library

diff --git a/php/Dockerfile b/php/Dockerfile
--- a/php/Dockerfile
+++ b/php/Dockerfile
@@ -1,39 +1,47 @@
-FROM buildpack-deps:jessie
-# building on work of MAINTAINER Eugene Ware <eugene@noblesamurai.com>
-MAINTAINER Dave Lane <dave@davelane.nz>
+FROM debian:jessie
+# modified from config by MAINTAINER https://github.com/helderco/
+MAINTAINER Dave Lane https://davelane.nz
 
-RUN apt-get update && apt-get install -y curl && rm -r /var/lib/apt/lists/*
+# persistent / runtime deps
+RUN apt-get update && apt-get install -y --no-install-recommends \
+      apt-utils \
+      ca-certificates \
+      curl \
+      librecode0 \
+      libmariadb-client-lgpl-dev \
+#      libmariadb-client-lgpl-dev-compat \
+      libmariadb2 \
+      libmysqlclient-dev \
+      libsqlite3-0 \
+      libxml2 \
+      mariadb-client \
+    && apt-get clean \
+    && rm -r /var/lib/apt/lists/*
 
-##<apache2>##
-RUN apt-get update && apt-get install -y \
-    apache2-bin apache2-dev apache2.2-common --no-install-recommends && \
-    rm -rf /var/lib/apt/lists/*
+# phpize deps
+RUN apt-get update && apt-get install -y --no-install-recommends \
+      autoconf \
+      file \
+      g++ \
+      gcc \
+      libc-dev \
+      make \
+      pkg-config \
+      re2c \
+    && apt-get clean \
+    && rm -r /var/lib/apt/lists/*
 
-RUN rm -rf /var/www/html && mkdir -p /var/lock/apache2 /var/run/apache2 \
-    /var/log/apache2 /var/www/html && \
-    chown -R www-data:www-data /var/lock/apache2 \
-    /var/run/apache2 /var/log/apache2 /var/www/html
+ENV PHP_INI_DIR /usr/local/etc/php
+RUN mkdir -p $PHP_INI_DIR/conf.d
 
-# Apache + PHP requires preforking Apache for best results
-RUN a2dismod mpm_event && a2enmod mpm_prefork
-
-RUN mv /etc/apache2/apache2.conf /etc/apache2/apache2.conf.dist
-COPY apache2.conf /etc/apache2/apache2.conf
-##</apache2>##
-
-RUN gpg --keyserver pgp.mit.edu --recv-keys \
-    0B96609E270F565C13292B24C13C70B87267B52D \
-    0A95E9A026542D53835E3F3A7DEC4E69FC9C83D7
-
-ENV GPG_KEYS 0B96609E270F565C13292B24C13C70B87267B52D \
-    0A95E9A026542D53835E3F3A7DEC4E69FC9C83D7 0E604491
+ENV GPG_KEYS 0B96609E270F565C13292B24C13C70B87267B52D 0A95E9A026542D53835E3F3A7DEC4E69FC9C83D7 0E604491
 RUN set -xe \
   && for key in $GPG_KEYS; do \
     gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
   done
 
 # compile openssl, otherwise --with-openssl won't work
-RUN CFLAGS="-fPIC" && OPENSSL_VERSION="1.0.2d" \
+RUN OPENSSL_VERSION="1.0.2k" \
       && cd /tmp \
       && mkdir openssl \
       && curl -sL "https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz" -o openssl.tar.gz \
@@ -41,48 +49,99 @@ RUN CFLAGS="-fPIC" && OPENSSL_VERSION="1.0.2d" \
       && gpg --verify openssl.tar.gz.asc \
       && tar -xzf openssl.tar.gz -C openssl --strip-components=1 \
       && cd /tmp/openssl \
-      && ./config shared && make && make install \
+      && ./config && make && make install \
       && rm -rf /tmp/*
 
 ENV PHP_VERSION 5.3.29
 
-ENV PHP_INI_DIR /usr/local/lib
-RUN mkdir -p $PHP_INI_DIR/conf.d
-
 # php 5.3 needs older autoconf
-RUN set -x \
-	&& apt-get update && apt-get install -y autoconf2.13 && rm -r /var/lib/apt/lists/* \
-	&& curl -SLO http://launchpadlibrarian.net/140087283/libbison-dev_2.7.1.dfsg-1_amd64.deb \
-	&& curl -SLO http://launchpadlibrarian.net/140087282/bison_2.7.1.dfsg-1_amd64.deb \
-	&& dpkg -i libbison-dev_2.7.1.dfsg-1_amd64.deb \
-	&& dpkg -i bison_2.7.1.dfsg-1_amd64.deb \
-	&& rm *.deb \
-	&& curl -SL "http://php.net/get/php-$PHP_VERSION.tar.bz2/from/this/mirror" -o php.tar.bz2 \
-	&& curl -SL "http://php.net/get/php-$PHP_VERSION.tar.bz2.asc/from/this/mirror" -o php.tar.bz2.asc \
-	&& gpg --verify php.tar.bz2.asc \
-	&& mkdir -p /usr/src/php \
-	&& tar -xf php.tar.bz2 -C /usr/src/php --strip-components=1 \
-	&& rm php.tar.bz2* \
-	&& cd /usr/src/php \
-	&& ./buildconf --force \
-	&& ./configure --disable-cgi \
-		$(command -v apxs2 > /dev/null 2>&1 && echo '--with-apxs2' || true) \
-    --with-config-file-path="$PHP_INI_DIR" \
-    --with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
-		--with-mysql \
-		--with-mysqli \
-		--with-pdo-mysql \
-		--with-openssl=/usr/local/ssl \
-	&& make -j"$(nproc)" \
-	&& make install \
-	&& dpkg -r bison libbison-dev \
-	&& apt-get purge -y --auto-remove autoconf2.13 \
-  && make clean
+# --enable-mysqlnd is included below because it's harder to compile after the fact the extensions are (since it's a plugin for several extensions, not an extension in itself)
+RUN buildDeps=" \
+                autoconf2.13 \
+                libcurl4-openssl-dev \
+                libfreetype6-dev \
+                libgd2-xpm-dev \
+                libjpeg-dev \
+                libpng12-0-dev \
+                libreadline6-dev \
+                librecode-dev \
+                libsqlite3-dev \
+                libssl-dev \
+                libxml2-dev \
+                libxpm-dev \
+                xz-utils \
+                zlib1g-dev \
+      " \
+      && set -x \
+      && apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* \
+      && curl -SL "http://php.net/get/php-$PHP_VERSION.tar.xz/from/this/mirror" -o php.tar.xz \
+      && curl -SL "http://php.net/get/php-$PHP_VERSION.tar.xz.asc/from/this/mirror" -o php.tar.xz.asc \
+      && gpg --verify php.tar.xz.asc \
+      && mkdir -p /usr/src/php \
+      && tar -xof php.tar.xz -C /usr/src/php --strip-components=1 \
+      && rm php.tar.xz* \
+      && cd /usr/src/php \
+      && ./configure \
+            --with-config-file-path="$PHP_INI_DIR" \
+            --with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
+            --enable-fpm \
+            --with-fpm-user=www-data \
+            --with-fpm-group=www-data \
+            --disable-cgi \
+            --enable-mysqlnd \
+            --with-mysql \
+            --with-curl \
+            --with-gd \
+            --with-openssl=/usr/local/ssl \
+            --with-readline \
+            --with-recode \
+            --with-zlib \
+      && make -j"$(nproc)" \
+      && make install \
+      && { find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true; } \
+      && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false $buildDeps \
+      && make clean
 
 COPY docker-php-* /usr/local/bin/
-COPY apache2-foreground /usr/local/bin/
 
 WORKDIR /var/www/html
 
-EXPOSE 80
-CMD ["apache2-foreground"]
+RUN set -ex \
+  && cd /usr/local/etc \
+  && if [ -d php-fpm.d ]; then \
+    # for some reason, upstream's php-fpm.conf.default has "include=NONE/etc/php-fpm.d/*.conf"
+    sed 's!=NONE/!=!g' php-fpm.conf.default | tee php-fpm.conf > /dev/null; \
+    cp php-fpm.d/www.conf.default php-fpm.d/www.conf; \
+  else \
+    # PHP 5.x don't use "include=" by default, so we'll create our own simple config that mimics PHP 7+ for consistency
+    mkdir php-fpm.d; \
+    cp php-fpm.conf.default php-fpm.d/www.conf; \
+    { \
+      echo '[global]'; \
+      echo 'include=etc/php-fpm.d/*.conf'; \
+    } | tee php-fpm.conf; \
+  fi \
+  && { \
+    echo '[global]'; \
+    echo 'error_log = /proc/self/fd/2'; \
+    echo; \
+    echo '[www]'; \
+    echo '; if we send this to /proc/self/fd/1, it never appears'; \
+    echo 'access.log = /proc/self/fd/2'; \
+    echo; \
+    echo '; Ensure worker stdout and stderr are sent to the main error log.'; \
+    echo 'catch_workers_output = yes'; \
+  } | tee php-fpm.d/docker.conf \
+  && { \
+    echo '[global]'; \
+    echo 'daemonize = no'; \
+    echo; \
+    echo '[www]'; \
+    echo 'listen = 9000'; \
+  } | tee php-fpm.d/zz-docker.conf
+
+# fix some weird corruption in this file
+RUN sed -i -e "" /usr/local/etc/php-fpm.d/www.conf
+
+EXPOSE 9000
+CMD["php-fpm"]
